name: progan_geodesics
channels:
 - defaults
dependencies:
 - python=3.6
 - numpy>=1.13.3
 - scipy>=1.0.0
 - cudatoolkit = 9.0
 - tensorflow-gpu <= 1.12.0
 #- moviepy>=0.2.3.2
 - Pillow>=3.1.1
 - lmdb >= 0.9
 - opencv=3.4.2
 - cryptography>=2.1.4
 - h5py>=2.7.1
 - six>=1.11.0
